services:
  benchmarks-node:
    container_name: benchmarks-node
    depends_on:
      - benchmarks-postgres
    build:
      context: .
      dockerfile: ./node/Dockerfile
    volumes:
      - .:/repo
    networks:
      - benchmarks-network
    ports:
      - '30000:30000'
    env_file:
      - .env
    environment:
      - NODE_ENVIRONMENT=production
      - PLATFORM=${PLATFORM:-express}
      - CLUSTER=${CLUSTER:-}

  benchmarks-go:
    container_name: benchmarks-go
    depends_on:
      - benchmarks-postgres
    build:
      context: .
      dockerfile: ./go/Dockerfile
    volumes:
      - .:/repo
    networks:
      - benchmarks-network
    ports:
      - '30001:30000'
    env_file:
      - .env

  benchmarks-rust:
    container_name: benchmarks-rust
    depends_on:
      - benchmarks-postgres
    build:
      context: .
      dockerfile: ./rust/Dockerfile
    volumes:
      - .:/repo
    networks:
      - benchmarks-network
    ports:
      - '30002:30000'
    env_file:
      - .env

  benchmarks-postgres:
    container_name: benchmarks-postgres
    image: postgres:16
    restart: always
    networks:
      - benchmarks-network
    ports:
      - '5432:5432'
    env_file:
      - .env

  benchmarks-wrk:
    container_name: benchmarks-wrk
    build:
      context: .
      dockerfile: ./wrk/Dockerfile
    networks:
      - benchmarks-network
    volumes:
      - .:/repo

networks:
  benchmarks-network:
    driver: bridge
