version: '3.8'

services:
  node:
    build:
      context: ../node
      dockerfile: ../docker/node.Dockerfile
    ports:
      - "3000:3000"
    networks:
      - benchmark_net
    env_file:
      - ../node/.env
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://postgres:100845@postgres:5432/demoRustdb

  rust:
    build:
      context: ../rust
      dockerfile: ../docker/rust.Dockerfile
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgres://postgres:100845@postgres:5432/demoRustdb
    networks:
      - benchmark_net


  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 100845
      POSTGRES_DB: demoRustdb
    ports:
      - "5432:5432"
    networks:
      - benchmark_net

  wrk:
    build:
      context: ..
      dockerfile: docker/wrk.Dockerfile
    depends_on:
      - node
      - rust
    networks:
      - benchmark_net
    entrypoint: ["sleep", "infinity"]
    volumes:
      - ../scripts:/scripts   # Mount thư mục scripts ở ngoài máy host vào trong container tại /scripts

networks:
  benchmark_net:
    driver: bridge
